name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install
        env:
          CI: true

      - name: npm test
        run: npm t

      - name: generate benchmarks
        run: |
          npm start
          cp results/benchmarks-${{ matrix.node-version }}.csv benchmarks.csv
          npm -s run graph > results/bar-graph-${{ matrix.node-version }}.svgs
          rm benchmarks.csv
        env:
          CI: true
          NODE_VERSION: ${{ matrix.node-version }}

      - name: push
        uses: github-actions-x/commit@v2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: master
          commit-message: 'feat: ${{ matrix.node-version }} adds auto-generated benchmarks and bar graph'
          rebase: 'true'
